### ISSUE TITLE
No variables update when using ProbSparse attention

### ISSUE THREAD

**Issue by victorxie996** [manjimnav/Informer-Tensorflow#1]
Hi manjimnav,

Many thanks for sharing this TF version code. One general question regarding to the gradient warnings as I met when excuting the code, it seems like the graidents for three linear projections are not able to update through back-prop because of the ProbSparse attention parts. 

After look into the code, I think the problem is caused by converting TF.tensor to numpy in line 101 where the tf gradient can't handle np arrays. Is there a way to avoid converting tensor to np arrays?

**Comment by manjimnav** [comment]
Hi @victorxie996 ,

Thanks to you for the support!. I am aware of this issue and I agree with you about the problem, but actually I have not found the way to change the tensor at the specific idexes without converting it to numpy array. Anyway, I am still reading documentation and trying to fix it :).

**Comment by manjimnav** [comment]
Fixed in 6d5d6b328ab594bbf57aade19b8752ccce2ff621 :)
